#!/usr/bin/env tsx
/**
 * `npm run specs:build` — regenerates `specs/` from the registry.
 *
 * The README has always promised this and it has never existed, so
 * `specs/architecture.md` was a dead link and `check-agents.ts` documented a
 * check ("every agent has a spec section in specs/agents/") it did not perform.
 *
 * GENERATED, NEVER HAND-EDITED. The registry is the single source of truth; a
 * hand-maintained spec is a second one that goes stale the first time an agent
 * is added. Every file written here carries that warning at the top.
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  AGENTS,
  REGISTRY_SUMMARY,
  SKILLS,
  STAGES,
  defaultSkillConfig,
} from '../shared/agent-registry'
import { TOOLS, TOOL_SUMMARY } from '../shared/tool-registry'
import { PLATFORMS } from '../shared/agent-contract'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SPECS = join(ROOT, 'specs')
const AGENTS_DIR = join(SPECS, 'agents')

const BANNER = `<!--
  GENERATED by \`npm run specs:build\` from shared/agent-registry.ts and
  shared/tool-registry.ts. Do not hand-edit: the next build overwrites it, and a
  hand-maintained copy of the registry is a second source of truth that goes
  stale the first time an agent changes.
-->
`

mkdirSync(AGENTS_DIR, { recursive: true })

/* ── specs/architecture.md ─────────────────────────────────────────────────── */

const stageRows = STAGES.map((stage) => {
  const inStage = AGENTS.filter((a) => a.stage === stage.id)
  return `| \`${stage.id}\` | ${stage.name} | ${inStage.map((a) => a.name).join(', ') || '—'} |`
}).join('\n')

const agentRows = AGENTS.map((agent) => {
  const skills = SKILLS.filter((s) => s.agentId === agent.id)
  const handsOff = agent.handsOffTo.length > 0 ? agent.handsOffTo.join(', ') : '—'
  return `| ${agent.name} | \`${agent.id}\` | ${agent.role} | \`${agent.stage}\` | ${skills.length} | ${handsOff} |`
}).join('\n')

const toolRows = TOOLS.map(
  (tool) => `| \`${tool.id}\` | ${tool.risk} | ${tool.summary.replace(/\|/g, '\\|')} |`,
).join('\n')

writeFileSync(
  join(SPECS, 'architecture.md'),
  `${BANNER}
# Architecture

**${REGISTRY_SUMMARY.agents} agents · ${REGISTRY_SUMMARY.stages} stages · ${REGISTRY_SUMMARY.skills} skills · ${REGISTRY_SUMMARY.knobs} knobs · ${TOOL_SUMMARY.tools} tools**

Eleven specialist agents run a seven-stage pipeline; the twelfth is the command
plane the operator talks to. Sequencing is derived from each agent's
\`handsOffTo\`, never special-cased in the orchestrator.

## Platforms

${PLATFORMS.map((p) => `- \`${p}\``).join('\n')}

## Stages

| Stage | Label | Agents |
|---|---|---|
${stageRows}

## Agents

| Name | Id | Role | Stage | Skills | Hands off to |
|---|---|---|---|---|---|
${agentRows}

## Tools the command plane may call

| Id | Risk | Summary |
|---|---|---|
${toolRows}

## The numbers that define the product

| What | Skill | Knob | Default |
|---|---|---|---|
| Top trending keywords | \`validation.keyword.trend\` | \`topKeywords\` | ${String(defaultSkillConfig('validation.keyword.trend').topKeywords)} |
| Hashtags per keyword | \`validation.hashtag.rank\` | \`topHashtagsPerKeyword\` | ${String(defaultSkillConfig('validation.hashtag.rank').topHashtagsPerKeyword)} |
| Consolidated hashtag set | \`analysis.hashtag.consolidate\` | \`topHashtags\` | ${String(defaultSkillConfig('analysis.hashtag.consolidate').topHashtags)} |
| Calendar slots per platform | \`calendar.rank.select\` | \`topPerPlatform\` | ${String(defaultSkillConfig('calendar.rank.select').topPerPlatform)} |
`,
  'utf8',
)

/* ── specs/agents/<id>.md ──────────────────────────────────────────────────── */

for (const agent of AGENTS) {
  const skills = SKILLS.filter((s) => s.agentId === agent.id)

  const skillSections = skills
    .map((skill) => {
      const knobs =
        skill.config.length === 0
          ? '_No configurable settings._'
          : ['| Knob | Default | Description |', '|---|---|---|']
              .concat(
                skill.config.map(
                  (field) =>
                    `| \`${field.key}\` | \`${String(field.default)}\` | ${field.description.replace(/\|/g, '\\|').replace(/\n/g, ' ')} |`,
                ),
              )
              .join('\n')

      return `### \`${skill.id}\`\n\n${skill.summary}\n\n${knobs}\n`
    })
    .join('\n')

  writeFileSync(
    join(AGENTS_DIR, `${agent.id}.md`),
    `${BANNER}
# ${agent.name} — ${agent.role}

- **Id**: \`${agent.id}\`
- **Stage**: \`${agent.stage}\`
- **Hands off to**: ${agent.handsOffTo.length > 0 ? agent.handsOffTo.map((h) => `\`${h}\``).join(', ') : '— (terminal)'}
- **Skills**: ${skills.length}
- **Handlers**: \`server/src/agents/${agent.id}/handlers.ts\`

${agent.description}

## Skills

${skillSections || '_This agent declares no skills._'}
`,
    'utf8',
  )
}

console.log(
  `  ✓ specs/architecture.md and ${AGENTS.length} agent spec(s) written to specs/agents/`,
)
