/**
 * THE SKILL BUILD
 *
 * `packages/skills/` is the versioned source of truth for runtime skills.
 * This script copies it into `packages/runtime/.claude/skills/` at build time.
 *
 * Why not just put them in the repo root `.claude/skills/`? Because Claude Code
 * would then load them as its *own* skills during development — so a request to
 * write a database migration might be answered by something that has decided it
 * is a content scraper. That is confusing and occasionally destructive.
 *
 * The runtime process runs with its `cwd` set to `packages/runtime/`, so the
 * Agent SDK finds them there. `packages/runtime/.claude/` is gitignored: it is
 * a build artifact, never edited and never committed.
 *
 *   npm run build-skills
 */

import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SOURCE = join(ROOT, 'packages/skills')
const TARGET = join(ROOT, 'packages/runtime/.claude/skills')

/* ═══════════════════════════════════════════════════════════════════════════
   VALIDATION — a SKILL.md is a specification, so it must actually specify
   ═══════════════════════════════════════════════════════════════════════════ */

/**
 * The sections that make a skill a requirements document rather than a
 * description. `Rules` and `Boundaries` are the two the eval suites are
 * derived from, so a skill missing either cannot be tested.
 */
const REQUIRED_SECTIONS = ['## Purpose', '## Inputs', '## Outputs', '## Rules', '## Boundaries']

interface Problem {
  skill: string
  message: string
}

function validate(name: string, body: string): Problem[] {
  const problems: Problem[] = []

  for (const section of REQUIRED_SECTIONS) {
    if (!body.includes(section)) {
      problems.push({ skill: name, message: `missing section: ${section}` })
    }
  }

  // Constraint 1: every number comes from the config registry. A literal
  // threshold in a skill body is exactly the drift this rule exists to stop.
  const bodyWithoutCode = body.replace(/```[\s\S]*?```/g, '')
  for (const [i, line] of bodyWithoutCode.split('\n').entries()) {
    // Ignore headings, config-key references, and prose that merely counts.
    if (line.startsWith('#') || line.includes('config.') || line.includes('`')) continue
    const match = /\b(threshold|weight|limit|cap|max|min)\b[^.\n]{0,20}?\b(\d+(\.\d+)?)\b/i.exec(line)
    if (match) {
      problems.push({
        skill: name,
        message: `line ${i + 1}: literal value "${match[2]}" near "${match[1]}" — every number must come from packages/config and be referenced by key`,
      })
    }
  }

  return problems
}

/* ═══════════════════════════════════════════════════════════════════════════
   BUILD
   ═══════════════════════════════════════════════════════════════════════════ */

if (!existsSync(SOURCE)) {
  console.error(`✗ ${SOURCE.replace(ROOT + '/', '')} does not exist. Nothing to build.`)
  process.exit(1)
}

const skillDirs = readdirSync(SOURCE).filter((entry) => {
  const path = join(SOURCE, entry)
  return statSync(path).isDirectory() && existsSync(join(path, 'SKILL.md'))
})

if (skillDirs.length === 0) {
  console.error(`✗ No SKILL.md files found under ${SOURCE.replace(ROOT + '/', '')}.`)
  process.exit(1)
}

console.log(`Building ${skillDirs.length} skills…\n`)

const problems: Problem[] = []
for (const name of skillDirs) {
  const body = readFileSync(join(SOURCE, name, 'SKILL.md'), 'utf8')
  problems.push(...validate(name, body))
}

if (problems.length > 0) {
  console.error('✗ Skill validation failed:\n')
  for (const problem of problems) {
    console.error(`  ${problem.skill}: ${problem.message}`)
  }
  console.error('\nSkills are the specification. A skill that does not specify cannot be built.')
  process.exit(1)
}

// A clean copy each time: a stale skill left behind would be loaded by the SDK
// and silently override the current one.
rmSync(TARGET, { recursive: true, force: true })
mkdirSync(TARGET, { recursive: true })

for (const name of skillDirs) {
  cpSync(join(SOURCE, name), join(TARGET, name), { recursive: true })
  console.log(`  ✓ ${name}`)
}

// A README in the artifact directory, so anyone who finds it knows not to edit it.
writeFileSync(
  join(TARGET, 'README.md'),
  `# BUILD ARTIFACT — DO NOT EDIT

Generated by \`scripts/build-skills.ts\` from \`packages/skills/\`.

Every change belongs in \`packages/skills/<name>/SKILL.md\`. Editing anything here
is lost on the next build, and is not version-controlled.

Last built: ${new Date().toISOString()}
`,
  'utf8',
)

console.log(
  `\n✓ ${skillDirs.length} skills built into packages/runtime/.claude/skills/ (gitignored build artifact).`,
)
