/**
 * BRAND ASSETS
 *
 * `public/brand/emblem.jpeg` is the company mark — the actual file, not a
 * reconstruction. This script embeds it once as a data URI in
 * `shared/emblem-data.ts`, so the sidebar, the creative renderers on both
 * tiers, the previews and the favicon all show the identical pixels, with no
 * network fetch and no drift.
 *
 *   npx tsx scripts/build-brand-assets.ts
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SOURCE = join(ROOT, 'public/brand/emblem.jpeg')

const bytes = readFileSync(SOURCE)
const dataUri = `data:image/jpeg;base64,${bytes.toString('base64')}`

writeFileSync(
  join(ROOT, 'shared/emblem-data.ts'),
  `/**
 * GENERATED by scripts/build-brand-assets.ts from public/brand/emblem.jpeg.
 * Do not edit. Replace the JPEG and re-run the script.
 *
 * The company emblem as a data URI, so every surface — browser, server-rendered
 * creatives, favicon — shows the identical file with no fetch.
 */

export const EMBLEM_DATA_URI =
  '${dataUri}'

/** Source pixel dimensions. The mark is square; the disc fills it. */
export const EMBLEM_SOURCE_SIZE = 373
`,
  'utf8',
)

/** The mark clipped to its disc — the JPEG has square white corners. */
const clipped = (size: number): string =>
  `<clipPath id="disc"><circle cx="${size / 2}" cy="${size / 2}" r="${size / 2}"/></clipPath>` +
  `<image href="${dataUri}" x="0" y="0" width="${size}" height="${size}" clip-path="url(#disc)" preserveAspectRatio="xMidYMid slice"/>`

writeFileSync(
  join(ROOT, 'public/favicon.svg'),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" role="img" aria-label="Ethara">
  <defs>${clipped(100)}</defs>
  <use href="#disc"/>
</svg>
`.replace('<defs>', '').replace('</defs>\n  <use href="#disc"/>', ''),
  'utf8',
)

writeFileSync(
  join(ROOT, 'public/logo.svg'),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 64" role="img" aria-label="Ethara.AI">
  <g transform="translate(4 4)">${clipped(56)}</g>
  <text x="70" y="41" font-family="Inter, system-ui, sans-serif" font-size="24" font-weight="600" letter-spacing="-0.02em" fill="#FFFFFF">Ethara<tspan fill="#EE00EE">.AI</tspan></text>
</svg>
`,
  'utf8',
)

console.log(`✓ embedded public/brand/emblem.jpeg (${bytes.length} bytes) into shared/emblem-data.ts, public/favicon.svg and public/logo.svg`)
