/**
 * THE BUNDLED DEMO DATASET
 *
 * Law 9 — degrade, never fail. With the API unreachable the store hydrates
 * from here and every screen still renders: the calendar populates, the
 * pipeline animates, drafts exist, analytics charts draw, and Ethara answers
 * on the in-bundle deterministic parser.
 *
 * The shape is `StatePayload` — byte-for-byte what `/api/state` returns — so
 * nothing downstream knows or cares which source it came from.
 *
 * Everything is generated by a seeded PRNG (mulberry32): same seed, same
 * numbers, every reload.
 */

import { BRAND, brandRulesAsKnowledge } from '@shared/brand-voice'
import { SEED_KEYWORDS } from '@shared/keywords'
import { AGENTS } from '@shared/agent-registry'
import type {
  ActivityEvent,
  AgentState,
  Draft,
  Hashtag,
  Idea,
  AssistantBrief,
  AssistantTurn,
  KnowledgeBuild,
  KnowledgeEntry,
  Keyword,
  KeywordSignal,
  MediaAsset,
  Platform,
  PlatformAnalytics,
  PublishedPost,
  ReviewQueueItem,
  ScrapedItem,
  Source,
  StatePayload,
} from '../types'
import { renderBrandSvg } from '../lib/image-gen'

/* ═══════════════════════════════════════════════════════════════════════════
   DETERMINISM
   ═══════════════════════════════════════════════════════════════════════════ */

function mulberry32(seed: number): () => number {
  let a = seed >>> 0
  return () => {
    a = (a + 0x6d2b79f5) >>> 0
    let t = a
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

const rand = mulberry32(20260908)

function ri(min: number, max: number): number {
  return Math.floor(rand() * (max - min + 1)) + min
}

function rf(min: number, max: number, dp = 2): number {
  return Number((rand() * (max - min) + min).toFixed(dp))
}

function pick<T>(list: readonly T[]): T {
  return list[Math.floor(rand() * list.length)] as T
}

/** Stable synthetic id — readable in the console, and unique per kind. */
let idCounter = 0
function id(prefix: string): string {
  idCounter += 1
  return `${prefix}-${String(idCounter).padStart(4, '0')}`
}

/* ═══════════════════════════════════════════════════════════════════════════
   DATES
   ═══════════════════════════════════════════════════════════════════════════ */

const NOW = new Date()

function iso(d: Date): string {
  return d.toISOString()
}

function isoDate(d: Date): string {
  return d.toISOString().slice(0, 10)
}

function addDays(d: Date, days: number): Date {
  const out = new Date(d)
  out.setDate(out.getDate() + days)
  return out
}

function minutesAgo(n: number): string {
  return iso(new Date(NOW.getTime() - n * 60_000))
}

function hoursAgo(n: number): string {
  return iso(new Date(NOW.getTime() - n * 3_600_000))
}

function daysAgo(n: number): string {
  return iso(addDays(NOW, -n))
}

function startOfWeek(d: Date): Date {
  const out = new Date(d)
  const day = out.getDay()
  out.setDate(out.getDate() + (day === 0 ? -6 : 1 - day))
  out.setHours(0, 0, 0, 0)
  return out
}

function lastSunday(d: Date): Date {
  const out = new Date(d)
  out.setDate(out.getDate() - (out.getDay() === 0 ? 7 : out.getDay()))
  out.setHours(6, 0, 0, 0)
  return out
}

function monthKey(back: number): string {
  const out = new Date(NOW.getFullYear(), NOW.getMonth() - back, 1)
  return `${out.getFullYear()}-${String(out.getMonth() + 1).padStart(2, '0')}`
}

function monthLabel(key: string): string {
  const [y, m] = key.split('-').map(Number)
  return new Date(y as number, (m as number) - 1, 1).toLocaleDateString('en-GB', {
    month: 'long',
    year: 'numeric',
  })
}

function daysInMonth(key: string): number {
  const [y, m] = key.split('-').map(Number)
  return new Date(y as number, m as number, 0).getDate()
}

const THIS_WEEK = startOfWeek(NOW)
const LAST_BUILD = lastSunday(NOW)
const MONTHS = [monthKey(3), monthKey(2), monthKey(1)]
const REPORTED_MONTH = MONTHS[2] as string

/* ═══════════════════════════════════════════════════════════════════════════
   KEYWORDS AND THEIR FOUR RUNS OF HISTORY
   ═══════════════════════════════════════════════════════════════════════════ */

const keywords: Keyword[] = SEED_KEYWORDS.map((k) => ({
  id: id('kw'),
  term: k.term,
  category: k.category,
  weight: k.weight,
  active: true,
  created_at: daysAgo(60),
}))

const KEYWORD_BY_TERM = new Map(keywords.map((k) => [k.term, k]))

/**
 * The five that trend, in rank order. Fixed rather than random so the
 * narrative across screens (theater → intelligence → calendar) is coherent.
 */
const TRENDING_TERMS = [
  'agentic AI',
  'reward modeling',
  'reinforcement learning',
  'RLHF',
  'post-training',
]

const TREND_REASONS: Record<string, string> = {
  'agentic AI':
    'Highest engagement velocity in the set: 41 posts this week carrying 68% more engagement than its four-run average.',
  'reward modeling':
    '3rd highest volume this week (34 posts) and the fastest-growing: engagement is up 52% against its four-run average.',
  'reinforcement learning':
    'The largest absolute volume (47 posts) with engagement steady within 4% of its four-run average — a reliable base, not a spike.',
  RLHF: 'Volume is flat but engagement per post rose 31%, concentrated in posts about annotator disagreement.',
  'post-training':
    'Smallest of the five by volume (22 posts) but the highest engagement per post at 214 — a narrow, highly engaged audience.',
}

/** Four historical runs plus the current one, so growth % is meaningful. */
const keywordSignals: KeywordSignal[] = []
for (const [runIndex, back] of [12, 9, 6, 3, 0].entries()) {
  const isCurrent = back === 0
  const capturedAt = daysAgo(back)
  const runId = id('run')

  const scored = keywords.map((k) => {
    const trendIndex = TRENDING_TERMS.indexOf(k.term)
    const trending = trendIndex >= 0
    const growth = trending ? rf(18, 68, 1) : rf(-22, 16, 1)
    const posts = trending ? ri(22, 47) : ri(3, 21)
    const engagement = posts * ri(64, 240)
    const base = Math.round((k.weight * 0.4 + (trending ? 44 : 12) + runIndex * 1.4) * rf(0.94, 1.06))
    return {
      keyword: k,
      trending,
      trendIndex,
      posts,
      engagement,
      growth,
      score: Math.max(9, Math.min(98, base)),
    }
  })

  const ranked = [...scored].sort((a, b) => {
    if (a.trending !== b.trending) return a.trending ? -1 : 1
    if (a.trending && b.trending) return a.trendIndex - b.trendIndex
    return b.score - a.score
  })

  for (const [i, s] of ranked.entries()) {
    keywordSignals.push({
      id: id('sig'),
      keyword_id: s.keyword.id,
      term: s.keyword.term,
      run_id: runId,
      post_count: s.posts,
      total_engagement: s.engagement,
      avg_engagement: (s.engagement / Math.max(1, s.posts)).toFixed(2),
      velocity: rf(2.4, 28.6).toFixed(2),
      growth_pct: s.growth.toFixed(2),
      trend_score: s.score,
      rank: i + 1,
      is_trending: isCurrent ? s.trending : s.trending && rand() > 0.25,
      trend_reason: s.trending ? (TREND_REASONS[s.keyword.term] ?? null) : null,
      captured_at: capturedAt,
    })
  }
}

/** The current run's signals — what every screen shows by default. */
const latestRunId = keywordSignals[keywordSignals.length - 1]?.run_id ?? null

/* ═══════════════════════════════════════════════════════════════════════════
   SOURCES AND SCRAPED ITEMS
   ═══════════════════════════════════════════════════════════════════════════ */

const sources: Source[] = [
  { id: id('src'), name: 'LinkedIn · keyword search', kind: 'linkedin', source_type: 'Social', url: null, trusted: true, enabled: true },
  { id: id('src'), name: 'LinkedIn · hashtag feeds', kind: 'linkedin', source_type: 'Social', url: null, trusted: true, enabled: true },
  { id: id('src'), name: 'LinkedIn · competitor pages', kind: 'linkedin', source_type: 'Competitor', url: null, trusted: true, enabled: true },
  { id: id('src'), name: 'arXiv cs.LG', kind: 'web', source_type: 'News', url: 'https://arxiv.org/list/cs.LG/recent', trusted: true, enabled: true },
  { id: id('src'), name: 'Import AI', kind: 'web', source_type: 'News', url: 'https://importai.substack.com', trusted: true, enabled: true },
  { id: id('src'), name: 'The Batch', kind: 'web', source_type: 'News', url: 'https://www.deeplearning.ai/the-batch/', trusted: true, enabled: true },
  { id: id('src'), name: 'Hacker News · AI', kind: 'web', source_type: 'Community', url: 'https://news.ycombinator.com', trusted: false, enabled: true },
  { id: id('src'), name: 'r/MachineLearning', kind: 'web', source_type: 'Community', url: 'https://reddit.com/r/MachineLearning', trusted: false, enabled: true },
  { id: id('src'), name: 'Ethara blog', kind: 'web', source_type: 'Website', url: 'https://ethara.ai/blog', trusted: true, enabled: true },
  { id: id('src'), name: 'X · AI research list', kind: 'x', source_type: 'Social', url: null, trusted: false, enabled: false },
  { id: id('src'), name: 'Instagram · brand account', kind: 'instagram', source_type: 'Social', url: null, trusted: true, enabled: true },
]

const AUTHORS: Array<{ name: string; headline: string; followers: number }> = [
  { name: 'Dr Anita Raghavan', headline: 'Research Scientist · post-training', followers: 18_400 },
  { name: 'Marcus Feld', headline: 'Head of AI Platform', followers: 42_100 },
  { name: 'Priya Nair', headline: 'ML Engineer · evaluation infrastructure', followers: 9_800 },
  { name: 'Tomas Lindqvist', headline: 'Founding Engineer · agent tooling', followers: 27_600 },
  { name: 'Rina Okafor', headline: 'Director of Applied Research', followers: 61_200 },
  { name: 'Daniel Weiss', headline: 'RL researcher', followers: 12_300 },
  { name: 'Sana Qureshi', headline: 'CTO · enterprise AI', followers: 33_900 },
  { name: 'Ben Hartley', headline: 'Staff Engineer · inference', followers: 15_700 },
]

const POST_BODIES: Array<{ title: string; snippet: string; tags: string[]; topic: string }> = [
  { title: 'The reward model is the specification', snippet: 'Every preference pair narrows what the policy is allowed to become. The pairs you did not collect are the behaviours you did not constrain.', tags: ['RewardModeling', 'RLHF', 'AIAlignment'], topic: 'reward modeling' },
  { title: 'Nine months of agent work, compressed', snippet: 'The model was never the constraint. Non-idempotent tools were. Unversioned schemas were. Errors the planner could not read were.', tags: ['AgenticAI', 'AIAgents', 'LLMOps'], topic: 'agentic AI' },
  { title: 'Process supervision generalises better than outcome reward', snippet: 'Rewarding intermediate reasoning beat outcome-only reward on every long-horizon task we tried, at roughly 2.3x labelling cost.', tags: ['ReinforcementLearning', 'RewardModeling', 'AIAlignment'], topic: 'reinforcement learning' },
  { title: 'Annotator disagreement is training signal', snippet: 'Majority vote throws away the most useful thing in your preference data. We now model the disagreement distribution instead of collapsing it.', tags: ['RLHF', 'SyntheticData', 'RewardModeling'], topic: 'RLHF' },
  { title: 'Post-training runs out of notebooks', snippet: 'Preference dataset lineage, reward model versioning, reproducible measurement of behavioural change. Three gaps, no owners.', tags: ['PostTraining', 'LLMFineTuning', 'AIInfrastructure'], topic: 'post-training' },
  { title: 'Determinism before ablations', snippet: 'If your environment is not deterministic given a seed, your ablations are opinions with error bars.', tags: ['AIEnvironments', 'ReinforcementLearning', 'AIResearch'], topic: 'AI environments' },
  { title: 'Benchmark saturation is a curriculum problem', snippet: 'When everyone scores 94%, the benchmark has stopped teaching. Contamination is the default assumption now, not the exception.', tags: ['AIBenchmarks', 'ModelEvaluation'], topic: 'AI benchmarks' },
  { title: 'One planner, four typed tools', snippet: 'We replaced a five-agent mesh with a single planner over four typed tools. Task success held; p95 latency fell by 81%.', tags: ['MultiAgentSystems', 'AgenticAI', 'AIAgents'], topic: 'multi-agent systems' },
  { title: 'Model collapse needs an unverified loop', snippet: 'Synthetic data degrades only under unverified self-sampling. Add a grounding signal and measured quality rises across six generations.', tags: ['SyntheticData', 'LLMFineTuning'], topic: 'synthetic data' },
  { title: 'Cost per solved task, not per token', snippet: 'Effective inference cost fell an order of magnitude from routing and caching. List price barely moved.', tags: ['InferenceOptimization', 'AIInfrastructure'], topic: 'inference optimization' },
  { title: 'The eval set outlived three models', snippet: 'The most durable AI artefact in most organisations is the evaluation set. Version it like code, because it is.', tags: ['ModelEvaluation', 'AIBenchmarks'], topic: 'model evaluation' },
  { title: 'Reward hacking is a spec review finding', snippet: 'Every hack is the policy correctly optimising something a human wrote carelessly. Review the reward like an API contract.', tags: ['RewardModeling', 'AIAlignment', 'AISafety'], topic: 'reward modeling' },
  { title: 'Confirmation design is the product', snippet: 'People want agents that ask before anything irreversible and get on with everything else. That is a UX decision, not a model capability.', tags: ['AgenticAI', 'AIAgents'], topic: 'agentic AI' },
  { title: 'Replay beats dashboards for agents', snippet: 'Re-running a past decision against the exact state and config it saw is what makes a non-deterministic system debuggable.', tags: ['LLMOps', 'AgenticAI', 'AIInfrastructure'], topic: 'agentic AI' },
  { title: 'Frontier evaluation is an environments problem', snippet: 'The hard part is not scoring the answer. It is building a world in which the question is meaningful and repeatable.', tags: ['AIEnvironments', 'ModelEvaluation', 'AIBenchmarks'], topic: 'AI environments' },
  { title: 'What enterprise AI adoption actually blocks on', snippet: 'Not capability. Procurement, evaluation evidence and an internal owner who can be paged.', tags: ['EnterpriseAI', 'AIAdoption'], topic: 'enterprise AI adoption' },
  { title: 'Fine-tuning is a distribution decision', snippet: 'Most teams reach for fine-tuning when what they need is retrieval and a better evaluation set.', tags: ['LLMFineTuning', 'ModelEvaluation'], topic: 'LLM fine-tuning' },
  { title: 'Frontier labs publish less, evaluate more', snippet: 'The shift in the last eighteen months is from capability papers to evaluation infrastructure. That is a maturity signal.', tags: ['FrontierModels', 'AIResearch'], topic: 'frontier models' },
  { title: 'Safety evaluation needs adversaries, not checklists', snippet: 'A checklist measures what you thought of. An adversary measures what you did not.', tags: ['AISafety', 'ModelEvaluation'], topic: 'AI safety evaluation' },
  { title: 'Engineering leadership in the agent era', snippet: 'The new skill is deciding which decisions stay human. Everything else is scheduling.', tags: ['EngineeringLeadership', 'AgenticAI'], topic: 'engineering leadership AI' },
]

const VERDICT_REASONS: Record<string, (t: string) => string> = {
  validated: (t) => `Relevance ${t} against the brand topic set, from a High-credibility author with a research headline — above the 70 accept threshold.`,
  needs_review: (t) => `Relevance scored ${t}, between the 40 reject and 70 accept thresholds. Credibility is Medium, so the verdict is yours.`,
  duplicate: (t) => `Dice similarity ${t} against an item captured four days ago. Linked to the original rather than dropped.`,
  rejected: (t) => `Relevance ${t}, below the 40 reject threshold: the body is a hiring post that mentions the keyword once.`,
}

const scraped: ScrapedItem[] = []
for (let i = 0; i < 42; i += 1) {
  const body = POST_BODIES[i % POST_BODIES.length] as (typeof POST_BODIES)[number]
  const author = pick(AUTHORS)
  const source = pick(sources.slice(0, 3))
  const keyword = KEYWORD_BY_TERM.get(body.topic) ?? (keywords[0] as Keyword)

  // Deliberate verdict spread so all four buckets are populated on first load.
  const verdict =
    i % 9 === 4 ? 'needs_review' : i % 11 === 7 ? 'duplicate' : i % 13 === 9 ? 'rejected' : 'validated'
  const relevance =
    verdict === 'validated' ? ri(72, 97) : verdict === 'needs_review' ? ri(48, 69) : verdict === 'duplicate' ? ri(60, 88) : ri(18, 38)

  const reactions = ri(40, 1_480)
  const comments = ri(3, 140)
  const reposts = ri(1, 190)

  scraped.push({
    id: id('item'),
    keyword_id: keyword.id,
    keyword_term: keyword.term,
    run_id: latestRunId,
    external_id: `urn:li:activity:${7_100_000_000_000 + i * 977}`,
    title: body.title,
    snippet: body.snippet,
    url: `https://www.linkedin.com/feed/update/urn:li:activity:${7_100_000_000_000 + i * 977}/`,
    source_name: source.name,
    source_type: source.source_type,
    author_name: author.name,
    author_headline: author.headline,
    author_followers: author.followers,
    hashtags: body.tags,
    engagement: reactions + comments * 3 + reposts * 5,
    reactions,
    comments,
    reposts,
    relevance,
    credibility: relevance >= 74 ? 'High' : relevance >= 46 ? 'Medium' : 'Low',
    freshness: ri(38, 99),
    is_duplicate: verdict === 'duplicate',
    duplicate_of_id: null,
    duplicate_of_tag: null,
    validation: verdict as ScrapedItem['validation'],
    verdict_reason: (VERDICT_REASONS[verdict] as (t: string) => string)(
      verdict === 'duplicate' ? '0.74' : String(relevance),
    ),
    capture_source: 'fixture',
    posted_at: hoursAgo(ri(2, 320)),
    scraped_at: minutesAgo(ri(2, 240)),
  } as ScrapedItem)
}

// Link every duplicate to a real original — nothing is ever orphaned.
const firstValidated = scraped.find((s) => s.validation === 'validated')
for (const item of scraped) {
  if (item.validation === 'duplicate' && firstValidated) item.duplicate_of_id = firstValidated.id
}

/* ═══════════════════════════════════════════════════════════════════════════
   HASHTAGS — five per trending keyword, plus the wider candidate pool
   ═══════════════════════════════════════════════════════════════════════════ */

const HASHTAGS_BY_KEYWORD: Record<string, string[]> = {
  'agentic AI': ['AgenticAI', 'AIAgents', 'LLMOps', 'ToolUse', 'AgentReliability'],
  'reward modeling': ['RewardModeling', 'RLHF', 'AIAlignment', 'PreferenceData', 'ProcessSupervision'],
  'reinforcement learning': ['ReinforcementLearning', 'DeepRL', 'PolicyOptimization', 'AIEnvironments', 'RLResearch'],
  RLHF: ['RLHF', 'HumanFeedback', 'AnnotatorAgreement', 'AlignmentResearch', 'PreferenceLearning'],
  'post-training': ['PostTraining', 'LLMFineTuning', 'AIInfrastructure', 'ModelAdaptation', 'InstructionTuning'],
}

const EXTRA_HASHTAGS = [
  'ModelEvaluation', 'AIBenchmarks', 'SyntheticData', 'MultiAgentSystems', 'InferenceOptimization',
  'FrontierModels', 'AISafety', 'EnterpriseAI', 'AIResearch', 'MLEngineering',
  'EvalHarness', 'ContextEngineering', 'RetrievalAugmented', 'OpenWeights', 'AIGovernance',
  'DataQuality', 'ScalingLaws', 'Interpretability', 'AIAdoption', 'EngineeringLeadership',
  'AIStrategy', 'GenAI', 'MachineLearning', 'DeepLearning', 'AICommunity',
  'PromptEngineering', 'VectorSearch', 'ModelServing', 'GPUCompute', 'AIProduct',
]

const HASHTAG_REASONS: Record<string, string> = {
  validated: 'Appeared in 14 of 41 captured posts for this keyword at 186 engagement per post — above both the volume floor and the 70 accept threshold.',
  needs_review: 'Only 3 occurrences this run, and two came from the same author. Volume is below the confidence floor, so the verdict is yours.',
  duplicate: 'Semantic alias of an already-ranked tag. Merged into the original and kept for lineage.',
  rejected: 'On the generic reach-bait list: high volume, no topical signal. Excluded by rule, not by score.',
}

const hashtags: Hashtag[] = []

for (const [keywordIndex, term] of TRENDING_TERMS.entries()) {
  const keyword = KEYWORD_BY_TERM.get(term) as Keyword
  const tags = HASHTAGS_BY_KEYWORD[term] as string[]
  for (const [i, tag] of tags.entries()) {
    const verdict = keywordIndex === 1 && i === 4 ? 'needs_review' : keywordIndex === 3 && i === 3 ? 'needs_review' : 'validated'
    const postCount = ri(6, 41) + (5 - i) * 3
    const engagement = postCount * ri(96, 260)
    hashtags.push({
      id: id('tag'),
      tag: tag.toLowerCase(),
      display_tag: tag,
      keyword_id: keyword.id,
      keyword_term: keyword.term,
      run_id: latestRunId,
      post_count: postCount,
      total_engagement: engagement,
      engagement_per_post: (engagement / postCount).toFixed(2),
      relevance: verdict === 'validated' ? ri(74, 98) : ri(52, 68),
      credibility: verdict === 'validated' ? 'High' : 'Medium',
      freshness: ri(58, 99),
      hashtag_score: Math.max(30, 96 - i * 6 - keywordIndex * 3),
      rank: i + 1,
      validation: verdict as Hashtag['validation'],
      verdict_reason: HASHTAG_REASONS[verdict] as string,
      duplicate_of_id: null,
      duplicate_of_tag: null,
      in_top_set: true,
      researched_at: i < 3 ? iso(LAST_BUILD) : null,
      first_seen_at: daysAgo(ri(4, 26)),
      last_seen_at: minutesAgo(ri(4, 180)),
    })
  }
}

for (const [i, tag] of EXTRA_HASHTAGS.entries()) {
  const verdict = i % 7 === 3 ? 'needs_review' : i % 11 === 8 ? 'duplicate' : i % 9 === 6 ? 'rejected' : 'validated'
  const postCount = ri(2, 24)
  const engagement = postCount * ri(48, 190)
  const keyword = keywords[(i * 3) % keywords.length] as Keyword
  hashtags.push({
    id: id('tag'),
    tag: tag.toLowerCase(),
    display_tag: tag,
    keyword_id: keyword.id,
    keyword_term: keyword.term,
    run_id: latestRunId,
    post_count: postCount,
    total_engagement: engagement,
    engagement_per_post: (engagement / postCount).toFixed(2),
    relevance: verdict === 'validated' ? ri(66, 92) : verdict === 'rejected' ? ri(12, 34) : ri(44, 68),
    credibility: verdict === 'validated' ? 'High' : verdict === 'rejected' ? 'Low' : 'Medium',
    freshness: ri(30, 96),
    hashtag_score: verdict === 'validated' ? ri(52, 84) : ri(18, 51),
    rank: null,
    validation: verdict as Hashtag['validation'],
    verdict_reason: HASHTAG_REASONS[verdict] as string,
    duplicate_of_id: null,
    duplicate_of_tag: null,
    in_top_set: false,
    researched_at: null,
    first_seen_at: daysAgo(ri(2, 30)),
    last_seen_at: minutesAgo(ri(10, 900)),
  })
}

// Duplicates link to a real original.
const firstRankedTag = hashtags.find((h) => h.in_top_set)
for (const h of hashtags) {
  if (h.validation === 'duplicate' && firstRankedTag) {
    h.duplicate_of_id = firstRankedTag.id
    h.duplicate_of_tag = firstRankedTag.display_tag
  }
}

// Every trend carries the URL a live run would have recorded — derived from the
// captured posts, never invented.
for (const h of hashtags) {
  h.feed_url = `https://www.linkedin.com/feed/hashtag/${encodeURIComponent(h.tag)}/`
  const carrier = [...scraped]
    .filter((s) => s.hashtags.includes(h.display_tag))
    .sort((a, b) => b.engagement - a.engagement)[0]
  h.top_post_url = carrier?.url ?? null
  h.top_post_title = carrier?.title ?? null
}
for (const signal of keywordSignals) {
  signal.search_url = `https://www.linkedin.com/search/results/content/?keywords=${encodeURIComponent(signal.term)}&sortBy=%22date_posted%22`
  const carrier = [...scraped]
    .filter((s) => s.keyword_id === signal.keyword_id)
    .sort((a, b) => b.engagement - a.engagement)[0]
  signal.top_post_url = carrier?.url ?? null
  signal.top_post_title = carrier?.title ?? null
}

/**
 * The consolidated top 25: the 5×5 validated set re-ranked globally, topped up
 * from the strongest remaining validated candidates.
 */
const topHashtags: Hashtag[] = [...hashtags]
  .filter((h) => h.validation === 'validated')
  .sort((a, b) => b.hashtag_score - a.hashtag_score)
  .slice(0, 25)
  .map((h, i) => ({ ...h, in_top_set: true, rank: i + 1 }))

const TOP_SET = new Set(topHashtags.map((h) => h.id))
for (const h of hashtags) h.in_top_set = TOP_SET.has(h.id)

/* ═══════════════════════════════════════════════════════════════════════════
   IDEAS — sixteen, with the top-10 rule already visible
   ═══════════════════════════════════════════════════════════════════════════ */

interface IdeaSeed {
  title: string
  description: string
  sourceTopic: string
  hashtag: string
  format: string
  angle: string
  audience: string
  confidence: number
  brandRelevance: number
  trendScore: number
  dayOffset: number
  time: string
  status: Idea['status']
  isNewTrend: boolean
  platform: Platform
}

const IDEA_SEEDS: IdeaSeed[] = [
  { title: 'Reward models are the product', description: 'The reward model is the specification. Whatever it rewards is what the system does in every case you did not enumerate.', sourceTopic: 'reward modeling', hashtag: 'RewardModeling', format: 'Thought Leadership', angle: 'Reframe the reward model as a product surface with an owner', audience: 'ML engineers and heads of AI', confidence: 94, brandRelevance: 96, trendScore: 92, dayOffset: 1, time: '10:30 AM', status: 'pending_leadership', isNewTrend: false, platform: 'linkedin' },
  { title: 'Calibration beats capacity in critics', description: 'A smaller well-calibrated reward model supervising a larger policy outperformed a same-size poorly calibrated one.', sourceTopic: 'reward modeling', hashtag: 'RewardModeling', format: 'Thought Leadership', angle: 'Cite the replication and draw the harness implication', audience: 'Researchers', confidence: 91, brandRelevance: 94, trendScore: 90, dayOffset: 3, time: '09:00 AM', status: 'in_review', isNewTrend: false, platform: 'linkedin' },
  { title: 'The environment was always the bottleneck', description: 'Agent reliability came from tool contracts and replay, not from a better model.', sourceTopic: 'agentic AI', hashtag: 'AgenticAI', format: 'Thought Leadership', angle: 'Attribute agent failure to environment design', audience: 'Engineering leaders', confidence: 93, brandRelevance: 92, trendScore: 95, dayOffset: 0, time: '11:00 AM', status: 'approved', isNewTrend: true, platform: 'linkedin' },
  { title: 'Confirmation design is the product', description: 'Users want agents that ask before anything irreversible and get on with everything else.', sourceTopic: 'agentic AI', hashtag: 'AgenticAI', format: 'Short Post', angle: 'Trust is a design output, not a model property', audience: 'Product and engineering', confidence: 89, brandRelevance: 88, trendScore: 93, dayOffset: 2, time: '02:00 PM', status: 'drafted', isNewTrend: true, platform: 'instagram' },
  { title: 'Process supervision generalises better', description: 'Rewarding intermediate reasoning beat outcome-only reward on every long-horizon task tried.', sourceTopic: 'reinforcement learning', hashtag: 'ReinforcementLearning', format: 'Carousel', angle: 'Cost-benefit of step-level labelling', audience: 'RL researchers', confidence: 90, brandRelevance: 95, trendScore: 88, dayOffset: 4, time: '10:00 AM', status: 'drafted', isNewTrend: false, platform: 'linkedin' },
  { title: 'Annotator disagreement is signal', description: 'The examples labellers argue about are the ones the reward model gets wrong in production.', sourceTopic: 'RLHF', hashtag: 'RLHF', format: 'Short Post', angle: 'Retain variance rather than aggregating it away', audience: 'Data and RLHF teams', confidence: 87, brandRelevance: 91, trendScore: 86, dayOffset: 1, time: '03:30 PM', status: 'suggested', isNewTrend: false, platform: 'facebook' },
  { title: 'Contamination is the default assumption', description: 'Rotating held-out sets, never published, plus distributions rather than averages.', sourceTopic: 'model evaluation', hashtag: 'ModelEvaluation', format: 'Thought Leadership', angle: 'Evaluation hygiene as a discipline', audience: 'Eval leads', confidence: 88, brandRelevance: 89, trendScore: 84, dayOffset: 2, time: '09:30 AM', status: 'suggested', isNewTrend: false, platform: 'linkedin' },
  { title: 'One agent with typed tools', description: 'Replacing a multi-agent mesh with one planner and four tools held task success at a fifth of the latency.', sourceTopic: 'multi-agent systems', hashtag: 'MultiAgentSystems', format: 'Thought Leadership', angle: 'Multi-agent is not free', audience: 'Architects', confidence: 86, brandRelevance: 87, trendScore: 89, dayOffset: 3, time: '01:00 PM', status: 'suggested', isNewTrend: false, platform: 'linkedin' },
  { title: 'Verification reverses model collapse', description: 'Synthetic data degrades only under unverified self-sampling. With a grounding signal quality rises.', sourceTopic: 'synthetic data', hashtag: 'SyntheticData', format: 'Thought Leadership', angle: 'Correct a widely repeated claim', audience: 'Data teams', confidence: 85, brandRelevance: 90, trendScore: 79, dayOffset: 4, time: '02:30 PM', status: 'drafted', isNewTrend: false, platform: 'facebook' },
  { title: 'Post-training has notebooks, not infrastructure', description: 'Pre-training is industrialised. Post-training is where the tooling gap now sits.', sourceTopic: 'post-training', hashtag: 'PostTraining', format: 'Short Post', angle: 'Name the specific missing tools', audience: 'Platform teams', confidence: 84, brandRelevance: 93, trendScore: 82, dayOffset: 0, time: '04:00 PM', status: 'suggested', isNewTrend: false, platform: 'linkedin' },
  { title: 'Cost per solved task, not per token', description: 'Effective inference cost fell an order of magnitude from routing and caching, not price cuts.', sourceTopic: 'inference optimization', hashtag: 'InferenceOptimization', format: 'Carousel', angle: 'Reframe the unit of cost', audience: 'CTOs', confidence: 83, brandRelevance: 78, trendScore: 87, dayOffset: 2, time: '11:30 AM', status: 'suggested', isNewTrend: true, platform: 'x' },
  { title: 'Determinism is a prerequisite', description: 'If the environment is not deterministic given a seed, the ablations are opinions.', sourceTopic: 'AI environments', hashtag: 'AIEnvironments', format: 'Short Post', angle: 'Reproducibility as engineering discipline', audience: 'RL engineers', confidence: 82, brandRelevance: 88, trendScore: 76, dayOffset: 3, time: '10:00 AM', status: 'suggested', isNewTrend: false, platform: 'linkedin' },
  { title: 'The eval set outlived three models', description: 'The most durable AI artefact in most organisations is the evaluation set, not the model.', sourceTopic: 'model evaluation', hashtag: 'ModelEvaluation', format: 'Thought Leadership', angle: 'Assets that survive migrations', audience: 'Heads of AI', confidence: 81, brandRelevance: 84, trendScore: 80, dayOffset: 1, time: '08:30 AM', status: 'suggested', isNewTrend: false, platform: 'linkedin' },
  { title: 'Reward hacking is a spec review finding', description: 'Every hack is the policy correctly optimising something written carelessly.', sourceTopic: 'reinforcement learning', hashtag: 'AIAlignment', format: 'Short Post', angle: 'Move the blame from policy to specification', audience: 'RL and alignment', confidence: 80, brandRelevance: 92, trendScore: 78, dayOffset: 4, time: '03:00 PM', status: 'suggested', isNewTrend: false, platform: 'linkedin' },
  { title: 'Replay, not dashboards', description: 'Re-running any past decision against the exact state and config it saw is what makes agents debuggable.', sourceTopic: 'agentic AI', hashtag: 'LLMOps', format: 'Thought Leadership', angle: 'Observability for non-deterministic systems', audience: 'Platform engineers', confidence: 79, brandRelevance: 83, trendScore: 85, dayOffset: 0, time: '01:30 PM', status: 'suggested', isNewTrend: false, platform: 'linkedin' },
  { title: 'Benchmarks finished teaching us', description: 'When everyone scores 94%, saturation is a curriculum problem, not a measurement one.', sourceTopic: 'AI benchmarks', hashtag: 'AIBenchmarks', format: 'Short Post', angle: 'What the next benchmark must ask', audience: 'Researchers', confidence: 77, brandRelevance: 82, trendScore: 81, dayOffset: 2, time: '04:30 PM', status: 'suggested', isNewTrend: false, platform: 'instagram' },
]

const SLOT_REASONS: Record<string, string[]> = {
  '10:30 AM': [
    'Tuesday 10:30 carries this account\'s highest median engagement over the last four weeks.',
    'The audience skews European working hours; 10:30 IST lands mid-morning for the largest segment.',
    'No other LinkedIn post is scheduled within four hours, so the two will not compete.',
    'Thought Leadership performs 34% above average when it opens the day rather than closing it.',
  ],
  '09:00 AM': [
    'Thursday 09:00 is the second strongest slot on this account by median reach.',
    'Research-heavy posts have historically landed better before midday here.',
    'Spread rule: the nearest scheduled post is 26 hours away.',
    'Carousel and long-form formats hold attention better early in the day.',
  ],
  default: [
    'The hour sits inside the configured 08:00–18:00 posting window.',
    'This platform has no other post within the six-hour spacing rule.',
    'Format fit for this platform scored 88 against the format×platform matrix.',
    'Weekend skip is on, so the nearest weekend day was excluded.',
  ],
}

function captionFor(seed: IdeaSeed): string {
  const tags = [seed.hashtag, 'AIResearch', 'Ethara'].slice(0, 3)
  return [
    seed.title + '.',
    '',
    seed.description,
    '',
    `The practical consequence: ${seed.angle.toLowerCase()}. We treat this as an engineering decision with an owner, not a research opinion.`,
    '',
    `At Ethara we build the environments and reward infrastructure this depends on.`,
    '',
    tags.map((t) => `#${t}`).join(' '),
  ].join('\n')
}

const ideas: Idea[] = []
const drafts: Record<string, Draft> = {}
const media: Record<string, MediaAsset> = {}

for (const [i, seed] of IDEA_SEEDS.entries()) {
  const ideaId = id('idea')
  const scheduled = addDays(THIS_WEEK, seed.dayOffset + (i >= 10 ? 7 : 0))
  const priority = Math.round(0.45 * seed.confidence + 0.35 * seed.brandRelevance + 0.2 * seed.trendScore)
  const hashtag = hashtags.find((h) => h.display_tag === seed.hashtag)
  const item = scraped.find((s) => s.keyword_term === seed.sourceTopic)

  ideas.push({
    id: ideaId,
    source_item_id: item?.id ?? null,
    hashtag_id: hashtag?.id ?? null,
    hashtag_display: seed.hashtag,
    title: seed.title,
    description: seed.description,
    source_topic: seed.sourceTopic,
    platform: seed.platform,
    alt_platforms:
      seed.platform === 'linkedin'
        ? [{ platform: 'facebook', score: ri(62, 80) }, { platform: 'x', score: ri(58, 78) }, { platform: 'instagram', score: ri(44, 68) }]
        : [{ platform: 'linkedin', score: ri(70, 92) }],
    scheduled_date: isoDate(scheduled),
    scheduled_time: seed.time,
    confidence: seed.confidence,
    priority_score: priority,
    platform_rank: null,
    calendar_slot: 'suggestion',
    status: seed.status,
    analysis: {
      format: seed.format,
      angle: seed.angle,
      audience: seed.audience,
      brandRelevance: seed.brandRelevance,
      trendScore: seed.trendScore,
      engagementLevel: seed.trendScore >= 88 ? 'High' : seed.trendScore >= 80 ? 'Medium' : 'Steady',
      bestDay: scheduled.toLocaleDateString('en-GB', { weekday: 'long' }),
      platformScore: ri(72, 96),
      slotReasons: SLOT_REASONS[seed.time] ?? (SLOT_REASONS.default as string[]),
    },
    feedback: [],
    is_new_trend: seed.isNewTrend,
    marketing_approved_by: seed.status === 'pending_leadership' || seed.status === 'approved' ? 'Ridhima' : null,
    marketing_approved_at: seed.status === 'pending_leadership' || seed.status === 'approved' ? hoursAgo(ri(3, 30)) : null,
    leadership_decision:
      seed.status === 'approved'
        ? { decision: 'approved', by: 'Arjun Mehta', at: hoursAgo(ri(1, 12)), published: false }
        : null,
    created_at: daysAgo(ri(1, 6)),
    updated_at: hoursAgo(ri(1, 40)),
  })

  // The first six ideas ship with a draft and a locally rendered creative, so
  // the calendar, review panel and previews all have real content on load.
  if (i < 8) {
    const body = captionFor(seed)
    drafts[`${ideaId}|${seed.platform}`] = {
      body,
      revision: i === 0 ? 3 : 1,
      model: 'ethara-writer',
      source: 'fixture',
      updatedAt: hoursAgo(ri(1, 20)),
    }
    media[`${ideaId}|${seed.platform}`] = renderBrandSvg({
      platform: seed.platform,
      headline: seed.title,
      kicker: seed.sourceTopic,
      concept: seed.format,
    })
  }
}

/**
 * The top-10 rule, applied exactly as `calendar.rank.select` applies it:
 * per platform independently, ranked by priority score.
 */
for (const platform of ['linkedin', 'instagram', 'x', 'facebook'] as Platform[]) {
  const forPlatform = ideas
    .filter((idea) => idea.platform === platform)
    .sort((a, b) => b.priority_score - a.priority_score)
  for (const [rank, idea] of forPlatform.entries()) {
    idea.platform_rank = rank + 1
    idea.calendar_slot = rank < 10 ? 'primary' : 'suggestion'
    idea.calendarSlot = idea.calendar_slot
    idea.platformRank = idea.platform_rank
    idea.draft = drafts[`${idea.id}|${idea.platform}`] ?? null
    idea.media = media[`${idea.id}|${idea.platform}`] ?? null
  }
}

/* ═══════════════════════════════════════════════════════════════════════════
   PUBLISHED POSTS
   ═══════════════════════════════════════════════════════════════════════════ */

interface PublishedSeed {
  title: string
  platform: Platform
  content: string
  ago: number
  reach: number
  impressions: number
  likes: number
  comments: number
  shares: number
  summary: string
  recommendation: string
}

const PUBLISHED_SEEDS: PublishedSeed[] = [
  { title: 'What a reward model actually specifies', platform: 'linkedin', content: 'A reward model is a specification written in examples rather than prose.\n\nEvery preference pair narrows what the policy is allowed to become. The pairs you did not collect are the behaviours you did not constrain, and the model will find them.\n\nWe now review reward definitions the way we review API contracts: before the work starts, with an owner named.\n\n#RewardModeling #ReinforcementLearning #AIAlignment', ago: 34, reach: 14_820, impressions: 18_940, likes: 742, comments: 68, shares: 94, summary: 'Reach ran 31% above the trailing four-post average, concentrated in non-follower impressions, which suggests the hook travelled beyond the existing audience.', recommendation: 'Lead with the specification framing again. It outperformed the mechanism-first opening by a wide margin.' },
  { title: 'Post-training is a discipline, not a phase', platform: 'linkedin', content: 'Pre-training infrastructure is something you can buy.\n\nPost-training infrastructure is something you still have to build, and most teams are running it out of notebooks. The specific gaps: preference dataset lineage, reward model versioning, and reproducible measurement of behavioural change.\n\nThe teams shipping reliably have separate owners for each.\n\n#PostTraining #LLMFineTuning #AIInfrastructure', ago: 31, reach: 11_240, impressions: 14_100, likes: 518, comments: 44, shares: 61, summary: 'Performed close to baseline: reach within 4% of the four-post average. Comment quality was high but volume was ordinary.', recommendation: 'The three-gap list worked. Cut the opening two lines — engagement began at the list.' },
  { title: 'Agents fail at the environment, not the model', platform: 'linkedin', content: 'Nine months of agent work, compressed.\n\nThe model was never the constraint. Non-idempotent tools were. Unversioned schemas were. Errors that the planner could not read were.\n\nWe stopped tuning prompts and started versioning the tool surface. Reliability moved more in three weeks than in the previous three months.\n\n#AgenticAI #AIAgents #LLMOps', ago: 27, reach: 21_460, impressions: 27_300, likes: 1_284, comments: 112, shares: 187, summary: 'The strongest post of the period: reach 89% above the trailing average and the highest share rate we have recorded, at 0.68%.', recommendation: 'Concrete failure lists outperform abstract argument here. Repeat the structure with a different subject.' },
  { title: 'Determinism before ablations', platform: 'linkedin', content: 'If your environment is not deterministic given a seed, your ablations are opinions with error bars.\n\nWe spent a month on reset semantics, observation schemas and separable reward plumbing. It paid for itself in the first week of real experiments.\n\n#AIEnvironments #ReinforcementLearning #AIResearch', ago: 24, reach: 9_840, impressions: 12_600, likes: 442, comments: 38, shares: 52, summary: 'Reach 18% below the trailing average. The subject is narrower than our usual and the audience reflected that.', recommendation: 'Keep publishing these — they attract the researcher segment — but do not schedule them opposite a broader post.' },
  { title: 'Annotator disagreement is training signal', platform: 'linkedin', content: 'Majority vote throws away the most useful thing in your preference data.\n\nThe examples your labellers argue about are, with striking regularity, the examples your reward model gets wrong in production. We now model the disagreement distribution instead of collapsing it.\n\n#RLHF #RewardModeling #SyntheticData', ago: 20, reach: 13_920, impressions: 17_400, likes: 684, comments: 71, shares: 88, summary: 'Reach 22% above the trailing average. Comments skewed toward practitioners describing their own aggregation approach.', recommendation: 'The counter-intuitive opening is doing the work. Keep leading with what conventional practice gets wrong.' },
  { title: 'The evaluation set is the durable artefact', platform: 'linkedin', content: 'Models get replaced. The evaluation set does not.\n\nOurs has outlived three model migrations and two architecture changes. It is versioned, reviewed and owned like production code, because that is what it is.\n\n#ModelEvaluation #AIBenchmarks #MLEngineering', ago: 17, reach: 12_380, impressions: 15_800, likes: 596, comments: 52, shares: 74, summary: 'Reach 8% above the trailing average with an unusually high save rate, which historically predicts later referral traffic.', recommendation: 'Add a concrete versioning example next time — the comments asked for one three times.' },
  { title: 'One planner beat five agents', platform: 'linkedin', content: 'We replaced a five-agent mesh with a single planner over four typed tools.\n\nTask success held. p95 latency fell 81%. Debugging went from archaeology to reading one trace.\n\nMulti-agent is a cost you should have to justify.\n\n#MultiAgentSystems #AgenticAI #AIAgents', ago: 14, reach: 18_640, impressions: 23_100, likes: 1_042, comments: 96, shares: 143, summary: 'Reach 61% above the trailing average. The latency figure was quoted in 14 reshares, which is what carried it.', recommendation: 'Put the hardest number in the second line. It travelled further than the framing did.' },
  { title: 'Verification reverses model collapse', platform: 'linkedin', content: 'Synthetic data does not inherently degrade a model.\n\nUnverified self-sampling does. Add a grounding signal and measured quality rises across six generations instead of falling.\n\n#SyntheticData #LLMFineTuning #AIResearch', ago: 11, reach: 10_960, impressions: 13_900, likes: 494, comments: 61, shares: 67, summary: 'Reach 6% below the trailing average, but comment depth was the highest in the period.', recommendation: 'This corrected a widely repeated claim. Corrections perform well here — keep one in the monthly mix.' },
  { title: 'Cost per solved task', platform: 'linkedin', content: 'Token price is not your inference cost.\n\nRouting, caching and early exit moved our effective cost per solved task by an order of magnitude while list prices barely moved.\n\nMeasure the unit you actually buy.\n\n#InferenceOptimization #AIInfrastructure #LLMOps', ago: 8, reach: 16_240, impressions: 20_400, likes: 872, comments: 79, shares: 118, summary: 'Reach 39% above the trailing average, with the strongest CTO-segment engagement recorded this quarter.', recommendation: 'The economics angle reaches a different audience than the research angle. Alternate them deliberately.' },
  { title: 'Reward hacking is a review finding', platform: 'linkedin', content: 'Every reward hack is a policy correctly optimising something a human wrote carelessly.\n\nWe moved reward specification into design review. Hacks did not disappear, but they now surface before training rather than after deployment.\n\n#RewardModeling #AIAlignment #AISafety', ago: 5, reach: 13_100, impressions: 16_700, likes: 622, comments: 58, shares: 81, summary: 'Reach 12% above the trailing average. Engagement was concentrated in the first four hours, which is unusual for this topic.', recommendation: 'Publishing at 09:00 rather than 10:30 pulled engagement earlier without reducing the total. Worth repeating.' },
  { title: 'Environments, not benchmarks', platform: 'instagram', content: 'Scoring an answer is easy.\n\nBuilding a world where the question is meaningful and repeatable is the actual research problem.\n\n#AIEnvironments #ModelEvaluation #AIResearch', ago: 22, reach: 6_420, impressions: 7_900, likes: 214, comments: 18, shares: 26, summary: 'Views 14% below the four-post average, with the drop concentrated in non-follower views.', recommendation: 'The single-statement format underperforms the two-panel carousel here by roughly a third. Prefer the carousel.' },
  { title: 'What post-training actually needs', platform: 'instagram', content: 'Three gaps, no owners:\n\nPreference dataset lineage.\nReward model versioning.\nReproducible behavioural measurement.\n\n#PostTraining #AIInfrastructure #MLEngineering', ago: 16, reach: 8_140, impressions: 9_800, likes: 302, comments: 24, shares: 41, summary: 'Views 19% above the four-post average. The list format held attention to the final panel at 71%.', recommendation: 'Three-item lists complete at a much higher rate than five-item ones on this account.' },
  { title: 'Alignment is an engineering discipline', platform: 'instagram', content: 'Not a philosophy seminar.\n\nSpecifications, reviews, owners, tests, and the willingness to be measured.\n\n#AIAlignment #AISafety #AIResearch', ago: 9, reach: 7_260, impressions: 8_900, likes: 268, comments: 21, shares: 33, summary: 'Views within 3% of the four-post average — a steady, unremarkable performance.', recommendation: 'Pair this with a concrete example next time. Abstract statements plateau at roughly this level.' },
  { title: 'Agent reliability is a tool-surface problem', platform: 'x', content: 'Agent reliability is a tool-surface problem, not a model problem.\n\nIdempotent tools. Versioned schemas. Errors a planner can read.\n\nThat is most of it.', ago: 19, reach: 4_820, impressions: 6_100, likes: 186, comments: 14, shares: 62, summary: 'Reach in line with this account\'s X baseline, with an unusually high repost ratio at 1.29%.', recommendation: 'Short declarative posts outperform threads on this account by a wide margin. Keep them under 40 words.' },
  { title: 'Benchmarks stopped teaching', platform: 'x', content: 'When everyone scores 94%, the benchmark has stopped teaching.\n\nSaturation is a curriculum problem, not a measurement one.', ago: 6, reach: 5_640, impressions: 7_200, likes: 224, comments: 19, shares: 78, summary: 'Reach 17% above the X baseline, driven by two reshares from accounts outside the usual network.', recommendation: 'The two-line form is working. Resist adding the supporting paragraph.' },
  { title: 'Reward models are specifications', platform: 'facebook', content: 'Every preference pair you collect narrows what a model is allowed to become. The pairs you did not collect are the behaviours you did not constrain.\n\nWe review reward definitions the way we review API contracts now — before the work starts, with an owner named.\n\n#RewardModeling #AIAlignment #AIResearch', ago: 13, reach: 3_840, impressions: 4_600, likes: 142, comments: 23, shares: 17, summary: 'The first Facebook reading on this account, so there is no trailing baseline to compare against yet. Comments came from practitioners rather than the general audience.', recommendation: 'Publish two more before drawing any conclusion. One post is a reading, not a trend.' },
  { title: 'The environment was the bottleneck', platform: 'facebook', content: 'Nine months of agent work, in one line: the model was never the constraint. The environment was.\n\nNon-idempotent tools, unversioned schemas, errors the planner could not read. We fixed the tool surface and reliability moved more in three weeks than in the previous three months.\n\n#AgenticAI #AIAgents #LLMOps', ago: 4, reach: 4_920, impressions: 5_900, likes: 198, comments: 31, shares: 26, summary: 'Reach 28% above the first Facebook post, on a sample of two — too small to call a baseline. Shares carried it further than likes did.', recommendation: 'The concrete failure list travelled. Keep the structure; the sample is still too small to conclude anything about the channel.' },
]

const published: PublishedPost[] = PUBLISHED_SEEDS.map((p) => {
  const engagementRate = ((p.likes + p.comments + p.shares) / p.impressions) * 100
  const assetId = id('media')
  return {
    id: id('post'),
    idea_id: null,
    title: p.title,
    platform: p.platform,
    content: p.content,
    status: 'published',
    external_id: `demo-${assetId}`,
    publish_mode: 'demo',
    published_at: isoDate(addDays(NOW, -p.ago)),
    history: [
      { step: 1, label: 'Draft generated by Caption Creator Agent', at: daysAgo(p.ago + 3) },
      { step: 2, label: 'Approved by Ridhima (Marketing)', at: daysAgo(p.ago + 1) },
      { step: 3, label: 'Final approval from Arjun Mehta (Leadership)', at: daysAgo(p.ago) },
      { step: 4, label: `Published to ${p.platform} in demo mode`, at: daysAgo(p.ago) },
    ],
    media_asset_id: assetId,
    analysis_summary: p.summary,
    analysis_recommendation: p.recommendation,
    reach: p.reach,
    impressions: p.impressions,
    likes: p.likes,
    comments: p.comments,
    shares: p.shares,
    engagement_rate: engagementRate.toFixed(2),
    metrics_captured_at: hoursAgo(ri(1, 20)),
    data_uri: renderBrandSvg({
      platform: p.platform,
      headline: p.title,
      kicker: 'Published',
      concept: 'Thought Leadership',
    }).dataUri,
  }
})

/* ═══════════════════════════════════════════════════════════════════════════
   KNOWLEDGE BASE
   ═══════════════════════════════════════════════════════════════════════════ */

const knowledge: KnowledgeEntry[] = []

/** The twenty brand rules live in the same table as everything learned. */
for (const rule of brandRulesAsKnowledge()) {
  knowledge.push({
    id: id('kb'),
    title: rule.title,
    category: rule.category,
    content: rule.content,
    source: 'Brand definition',
    sources: [],
    hashtag_id: null,
    hashtag_display: null,
    tags: ['brand'],
    confidence: rule.confidence,
    evidence_count: 1,
    active: true,
    origin: 'brand',
    build_id: null,
    created_at: daysAgo(90),
  })
}

const LEARNED: Array<{ title: string; category: string; content: string; confidence: 'High' | 'Medium' | 'Low' }> = [
  { title: 'Open with the counter-intuitive claim', category: 'User Feedback', content: 'Ridhima has moved the contrarian line to the first sentence on four consecutive drafts. Posts that open on the correction reach 22–31% above the trailing average; posts that open on context sit at or below it.', confidence: 'High' },
  { title: 'Hard numbers belong in line two', category: 'High Performer', content: 'The three strongest posts of the last month all placed their strongest figure in the second line. Reshare quotes almost always contain that figure.', confidence: 'High' },
  { title: 'Three-item lists complete; five-item lists do not', category: 'Platform Preference', content: 'On Instagram carousels, three-panel lists hold 71% of viewers to the final panel. Five-panel lists drop to 38%.', confidence: 'High' },
  { title: 'No emoji, on any platform', category: 'Brand Voice', content: 'The emoji budget is zero and has never been relaxed. Two drafts that included one were corrected by the operator before approval.', confidence: 'High' },
  { title: 'X posts stay under forty words', category: 'Platform Preference', content: 'Short declarative posts outperform threads on this account. The two best X posts were both two lines.', confidence: 'Medium' },
  { title: 'CTO segment responds to economics, not research', category: 'Audience Insight', content: 'The cost-per-solved-task post recorded the strongest CTO-segment engagement of the quarter. Research-framed posts reach researchers; economics-framed posts reach buyers.', confidence: 'High' },
  { title: 'Avoid scheduling two LinkedIn posts within six hours', category: 'Platform Preference', content: 'Two posts four hours apart split reach rather than compounding it: the second landed 43% below its expected baseline.', confidence: 'Medium' },
  { title: 'Corrections perform well', category: 'High Performer', content: 'Posts that correct a widely repeated claim draw deeper comments than posts that assert something new, even when total reach is lower.', confidence: 'Medium' },
  { title: 'Tuesday 10:30 is the strongest LinkedIn slot', category: 'Platform Preference', content: 'Median reach at Tuesday 10:30 over four weeks is 34% above the account average. Thursday 09:00 is second.', confidence: 'High' },
  { title: 'Do not claim results we have not published', category: 'Compliance Rule', content: 'A draft citing an internal benchmark figure was rejected by Leadership. Unpublished numbers require internal approval before they appear in a caption.', confidence: 'High' },
  { title: 'Rejected: "excited to announce" framing', category: 'Rejected Post', content: 'Leadership rejected a draft for promotional tone: "Tone is too promotional for a research audience." The phrase was replaced with a declarative opening and re-approved.', confidence: 'High' },
  { title: 'Carousel outperforms single image on Instagram', category: 'Platform Preference', content: 'Carousels beat single-panel posts by roughly a third in views on this account. The single-statement format underperforms consistently.', confidence: 'Medium' },
]

for (const entry of LEARNED) {
  knowledge.push({
    id: id('kb'),
    title: entry.title,
    category: entry.category,
    content: entry.content,
    source: 'Learning Agent',
    sources: [],
    hashtag_id: null,
    hashtag_display: null,
    tags: ['learned'],
    confidence: entry.confidence,
    evidence_count: ri(2, 6),
    active: true,
    origin: 'learned',
    build_id: null,
    created_at: daysAgo(ri(3, 40)),
  })
}

const RESEARCH: Array<{ title: string; content: string; hashtag: string; sources: Array<{ title: string; url: string }> }> = [
  { title: 'Process supervision outperforms outcome reward on long-horizon tasks', content: 'Two independent replications this quarter report that step-level reward beats outcome-only reward on multi-step reasoning, at roughly 2.3x labelling cost. The gap widens with horizon length.', hashtag: 'RewardModeling', sources: [{ title: 'Step-level reward modelling at scale', url: 'https://arxiv.org/abs/2501.04412' }, { title: 'Replication notes on process supervision', url: 'https://www.interconnects.ai/p/process-supervision-replication' }, { title: 'The Batch · reward modelling roundup', url: 'https://www.deeplearning.ai/the-batch/' }] },
  { title: 'Agent failures concentrate in the tool surface', content: 'An analysis of 1,400 production agent traces attributes 62% of failures to tool contract issues — non-idempotent calls, unversioned schemas and unparseable errors — rather than to model reasoning.', hashtag: 'AgenticAI', sources: [{ title: 'What breaks production agents', url: 'https://arxiv.org/abs/2502.11930' }, { title: 'Agent reliability field notes', url: 'https://importai.substack.com' }] },
  { title: 'Model collapse requires an unverified loop', content: 'Recent work shows synthetic data degrades quality only under unverified self-sampling. With a verification or grounding signal in the loop, measured quality improves across at least six generations.', hashtag: 'SyntheticData', sources: [{ title: 'Verification and synthetic data quality', url: 'https://arxiv.org/abs/2501.09877' }, { title: 'Revisiting model collapse', url: 'https://www.nature.com/articles/s41586-024-07566-y' }, { title: 'Synthetic data survey update', url: 'https://arxiv.org/abs/2502.03318' }] },
  { title: 'Benchmark contamination is now assumed, not tested for', content: 'Leading evaluation groups have moved to rotating held-out sets that are never published, and report distributions rather than single averages. Three major benchmarks adopted this in the last quarter.', hashtag: 'ModelEvaluation', sources: [{ title: 'Contamination-resistant evaluation', url: 'https://arxiv.org/abs/2501.15522' }, { title: 'Holdout rotation in practice', url: 'https://blog.eleuther.ai/holdout-rotation/' }] },
  { title: 'Annotator disagreement predicts reward model error', content: 'Preference pairs with low inter-annotator agreement are disproportionately the pairs on which the trained reward model later errs. Modelling the disagreement distribution improves robustness on ambiguous inputs.', hashtag: 'RLHF', sources: [{ title: 'Disagreement-aware preference learning', url: 'https://arxiv.org/abs/2502.07741' }, { title: 'Annotation quality in RLHF pipelines', url: 'https://arxiv.org/abs/2501.12208' }] },
  { title: 'Single-planner architectures match multi-agent meshes at lower latency', content: 'Several teams report replacing multi-agent architectures with one planner over typed tools, holding task success while cutting p95 latency by 60–85%. Multi-agent gains appear mainly where tasks are genuinely parallel.', hashtag: 'MultiAgentSystems', sources: [{ title: 'When multi-agent helps', url: 'https://arxiv.org/abs/2502.02214' }, { title: 'Planner-centric agent design', url: 'https://www.anthropic.com/engineering' }] },
  { title: 'Post-training tooling is the named gap', content: 'Practitioner surveys this quarter consistently name three missing pieces: preference dataset lineage, reward model versioning and reproducible behavioural measurement.', hashtag: 'PostTraining', sources: [{ title: 'State of post-training tooling', url: 'https://www.latent.space/p/post-training-tooling' }, { title: 'ML platform survey 2026', url: 'https://arxiv.org/abs/2501.18004' }] },
  { title: 'Inference cost is falling through routing, not price', content: 'Reported effective cost per solved task fell roughly an order of magnitude over eighteen months. The drivers are routing, caching and early exit, not list-price reductions.', hashtag: 'InferenceOptimization', sources: [{ title: 'Inference economics 2026', url: 'https://arxiv.org/abs/2502.09912' }, { title: 'Serving cost teardown', url: 'https://www.semianalysis.com' }] },
  { title: 'Determinism is a precondition for credible ablations', content: 'Environment reproducibility — seeded resets, versioned observation schemas, separable reward plumbing — is now treated as a prerequisite for publishing ablation results in RL work.', hashtag: 'AIEnvironments', sources: [{ title: 'Reproducibility in RL environments', url: 'https://arxiv.org/abs/2501.06630' }, { title: 'Environment design guidelines', url: 'https://farama.org/blog' }] },
  { title: 'Calibration matters more than critic size', content: 'A smaller, well-calibrated reward model supervising a larger policy outperformed a same-size but poorly calibrated critic across three task families.', hashtag: 'RewardModeling', sources: [{ title: 'Critic calibration study', url: 'https://arxiv.org/abs/2502.04455' }, { title: 'Reward model calibration notes', url: 'https://www.interconnects.ai/p/calibration' }] },
  { title: 'Alignment work is professionalising into engineering practice', content: 'Specification review, named owners and regression suites for behaviour are appearing in alignment workflows at several labs, replacing ad-hoc red-teaming.', hashtag: 'AIAlignment', sources: [{ title: 'Alignment engineering practices', url: 'https://arxiv.org/abs/2501.14090' }, { title: 'Specification review in practice', url: 'https://www.alignmentforum.org' }] },
  { title: 'Evaluation harnesses outlive the models they measure', content: 'Organisations report evaluation suites surviving three or more model migrations, making them the longest-lived AI artefact in the stack.', hashtag: 'AIBenchmarks', sources: [{ title: 'Longevity of evaluation infrastructure', url: 'https://arxiv.org/abs/2502.01188' }, { title: 'Eval infrastructure retrospective', url: 'https://blog.eleuther.ai/eval-infra/' }] },
  { title: 'Enterprise adoption blocks on evidence, not capability', content: 'Procurement cycles cite missing evaluation evidence and the absence of an internal owner far more often than model capability as the blocker.', hashtag: 'EnterpriseAI', sources: [{ title: 'Enterprise AI adoption survey', url: 'https://www.mckinsey.com/capabilities/quantumblack' }, { title: 'What blocks deployment', url: 'https://arxiv.org/abs/2501.20114' }] },
  { title: 'Open-weight models close the gap on narrow tasks', content: 'On task-specific evaluations with good harnesses, open-weight models now land within single-digit percentages of frontier closed models, while remaining well behind on open-ended reasoning.', hashtag: 'FrontierModels', sources: [{ title: 'Open vs closed on narrow tasks', url: 'https://arxiv.org/abs/2502.06002' }, { title: 'Open-weight capability tracking', url: 'https://epoch.ai/trends' }] },
  { title: 'Safety evaluation is moving from checklists to adversaries', content: 'Automated adversarial evaluation is replacing static checklists in published safety cases, on the basis that a checklist measures only anticipated failure modes.', hashtag: 'AISafety', sources: [{ title: 'Adversarial safety evaluation', url: 'https://arxiv.org/abs/2501.17755' }, { title: 'Safety case methodology', url: 'https://www.gov.uk/government/organisations/ai-safety-institute' }] },
]

const buildId = id('build')
for (const entry of RESEARCH) {
  const tag = hashtags.find((h) => h.display_tag === entry.hashtag)
  knowledge.push({
    id: id('kb'),
    title: entry.title,
    category: 'Research',
    content: entry.content,
    source: 'Parallel Web Systems',
    sources: entry.sources.map((s) => ({ ...s, publishedAt: daysAgo(ri(4, 30)).slice(0, 10) })),
    hashtag_id: tag?.id ?? null,
    hashtag_display: entry.hashtag,
    tags: ['research', entry.hashtag],
    confidence: entry.sources.length >= 3 ? 'High' : 'Medium',
    evidence_count: entry.sources.length,
    active: true,
    origin: 'research',
    build_id: buildId,
    created_at: iso(LAST_BUILD),
  })
}

// One entry switched off, so the power toggle has something to demonstrate.
const toggledOff = knowledge.find((k) => k.origin === 'learned' && k.title.startsWith('Corrections'))
if (toggledOff) toggledOff.active = false

const knowledgeBuild: KnowledgeBuild = {
  id: buildId,
  trigger: 'cron',
  status: 'completed',
  hashtags_researched: 25,
  entries_written: RESEARCH.length,
  entries_merged: 4,
  sources_cited: RESEARCH.reduce((n, r) => n + r.sources.length, 0),
  research_source: 'fixture',
  started_at: iso(LAST_BUILD),
  finished_at: iso(new Date(LAST_BUILD.getTime() + 11 * 60_000)),
  summary: {
    fallbackReason: 'PARALLEL_API_KEY is not set, so the build ran on the bundled research corpus.',
  },
  error: null,
}

/* ═══════════════════════════════════════════════════════════════════════════
   ANALYTICS
   ═══════════════════════════════════════════════════════════════════════════ */

const REPORTED_LINKEDIN = {
  impressions: 79_554,
  engagements: 16_665,
  pageViews: 59_147,
  followerGrowth: 2_312,
  organicShare: 99.8,
  lifePageViews: 12_493,
}

const REPORTED_INSTAGRAM = {
  views: 72_970,
  uniqueViewers: 12_896,
  interactions: 795,
  followerGrowth: 70,
  growthPct: 11.8,
  nonFollowerShare: 86.1,
}

/** Weekday-weighted daily series that sums exactly to the monthly headline. */
function dailySeries(key: string, total: number): Array<{ date: string; value: number }> {
  const days = daysInMonth(key)
  const [y, m] = key.split('-').map(Number)
  const weights: number[] = []
  for (let day = 1; day <= days; day += 1) {
    const dow = new Date(y as number, (m as number) - 1, day).getDay()
    weights.push((dow === 0 || dow === 6 ? 0.34 : 1) * rf(0.78, 1.24, 4))
  }
  const sum = weights.reduce((a, b) => a + b, 0)
  const series = weights.map((w, i) => ({
    date: `${key}-${String(i + 1).padStart(2, '0')}`,
    value: Math.max(0, Math.round((w / sum) * total)),
  }))
  const drift = total - series.reduce((n, d) => n + d.value, 0)
  if (drift !== 0) {
    let peak = 0
    for (const [i, d] of series.entries()) if (d.value > (series[peak] as { value: number }).value) peak = i
    ;(series[peak] as { value: number }).value += drift
  }
  return series
}

const analytics: PlatformAnalytics[] = []
const liCurve = [0.71, 0.85, 1]
const igCurve = [0.66, 0.82, 1]

for (const [i, key] of MONTHS.entries()) {
  const reported = key === REPORTED_MONTH
  const liF = liCurve[i] as number
  const igF = igCurve[i] as number

  const liImpressions = Math.round(REPORTED_LINKEDIN.impressions * liF)
  const liEngagements = Math.round(REPORTED_LINKEDIN.engagements * liF)

  analytics.push({
    id: id('an'),
    platform: 'linkedin',
    month: key,
    label: monthLabel(key),
    is_reported: reported,
    metrics: {
      impressions: liImpressions,
      engagements: liEngagements,
      pageViews: Math.round(REPORTED_LINKEDIN.pageViews * liF),
      followerGrowth: Math.round(REPORTED_LINKEDIN.followerGrowth * liF),
      organicShare: reported ? REPORTED_LINKEDIN.organicShare : rf(98.4, 99.7, 1),
      lifePageViews: Math.round(REPORTED_LINKEDIN.lifePageViews * liF),
      engagementRate: Number(((liEngagements / liImpressions) * 100).toFixed(2)),
      reach: Math.round(liImpressions * 0.78),
    },
    daily: dailySeries(key, liImpressions),
  })

  const igViews = Math.round(REPORTED_INSTAGRAM.views * igF)
  const igInteractions = Math.round(REPORTED_INSTAGRAM.interactions * igF)

  analytics.push({
    id: id('an'),
    platform: 'instagram',
    month: key,
    label: monthLabel(key),
    is_reported: reported,
    metrics: {
      views: igViews,
      uniqueViewers: Math.round(REPORTED_INSTAGRAM.uniqueViewers * igF),
      interactions: igInteractions,
      followerGrowth: reported ? REPORTED_INSTAGRAM.followerGrowth : Math.round(REPORTED_INSTAGRAM.followerGrowth * igF),
      growthPct: reported ? REPORTED_INSTAGRAM.growthPct : rf(6.2, 10.4, 1),
      nonFollowerShare: reported ? REPORTED_INSTAGRAM.nonFollowerShare : rf(79.2, 85.4, 1),
      engagementRate: Number(((igInteractions / igViews) * 100).toFixed(2)),
      reach: Math.round(REPORTED_INSTAGRAM.uniqueViewers * igF),
    },
    daily: dailySeries(key, igViews),
  })
}

/* ═══════════════════════════════════════════════════════════════════════════
   AGENT STATE, ACTIVITY AND THE REVIEW QUEUE
   ═══════════════════════════════════════════════════════════════════════════ */

const AGENT_TASKS: Record<string, string> = {
  assistant: 'Watching · last sweep found 2 signals',
  scraping: 'Idle · last run captured 42 posts across 12 keywords',
  validation: 'Needs review · 9 items awaiting a verdict',
  analysis: 'Idle · consolidated 25 hashtags last run',
  calendar: 'Idle · 16 ideas placed, 13 on the calendar',
  caption: 'Idle · 8 drafts written this week',
  image: 'Idle · rendering locally, no model configured',
  review: 'Waiting · 1 draft in review',
  knowledge: `Idle · last build ${RESEARCH.length} entries from 25 hashtags`,
  publishing: 'Idle · 15 posts published in demo mode',
  analytics: 'Idle · metrics refreshed 2 hours ago',
  learning: 'Idle · 12 lessons written back',
}

const agents: AgentState[] = AGENTS.map((agent) => ({
  agent_id: agent.id,
  status: agent.id === 'validation' ? 'needs_review' : agent.id === 'review' ? 'waiting' : 'idle',
  current_task: AGENT_TASKS[agent.id] ?? 'Idle',
  last_run: hoursAgo(ri(1, 26)),
  processed: ri(40, 480),
  success_rate: ri(92, 100),
}))

const ACTIVITY_SEEDS: Array<{ agent: string; message: string; status: ActivityEvent['status']; minutes: number }> = [
  { agent: 'scraping', message: 'APIFY_API_TOKEN is not set — the run used the bundled LinkedIn corpus.', status: 'warn', minutes: 214 },
  { agent: 'scraping', message: 'Captured 42 posts across 12 keywords and harvested 60 hashtag candidates.', status: 'ok', minutes: 212 },
  { agent: 'validation', message: 'Ranked 20 keywords · 5 trending. agentic AI leads on engagement velocity, up 68% on its four-run average.', status: 'ok', minutes: 208 },
  { agent: 'validation', message: '38 validated · 9 needs review · 4 duplicate · 9 rejected. Nine items are waiting on a verdict.', status: 'warn', minutes: 206 },
  { agent: 'analysis', message: 'Consolidated 25 hashtags across the five trending keywords and re-ranked globally.', status: 'ok', minutes: 203 },
  { agent: 'calendar', message: '16 ideas formed. Top 10 per platform took a calendar slot; 3 went to More suggestions.', status: 'ok', minutes: 199 },
  { agent: 'knowledge', message: `Sunday build complete · ${RESEARCH.length} entries written, 4 merged, ${knowledgeBuild.sources_cited} sources cited.`, status: 'ok', minutes: 186 },
  { agent: 'caption', message: 'Wrote 8 drafts grounded in 14 active Knowledge Base entries.', status: 'ok', minutes: 122 },
  { agent: 'image', message: 'Rendered 8 creatives with the local brand renderer — no image model is configured.', status: 'warn', minutes: 118 },
  { agent: 'review', message: '"Reward models are the product" passed the twenty-rule check and went to Leadership.', status: 'ok', minutes: 94 },
  { agent: 'analytics', message: 'Instagram reach is 14% below its four-week average; the drop is concentrated in non-follower views.', status: 'warn', minutes: 62 },
  { agent: 'learning', message: 'Learned: hard numbers belong in line two. Confidence raised to High after a third confirmation.', status: 'ok', minutes: 41 },
  { agent: 'assistant', message: 'Morning briefing composed: three changes and one recommendation.', status: 'ok', minutes: 18 },
]

const activity: ActivityEvent[] = ACTIVITY_SEEDS.map((a) => ({
  id: id('act'),
  agent_id: a.agent as ActivityEvent['agent_id'],
  message: a.message,
  status: a.status,
  entity_type: null,
  entity_id: null,
  created_at: minutesAgo(a.minutes),
}))

const reviewQueue: ReviewQueueItem[] = []
for (const h of hashtags.filter((x) => x.validation === 'needs_review').slice(0, 5)) {
  reviewQueue.push({
    id: id('rq'),
    kind: 'hashtag',
    entity_id: h.id,
    reason: h.verdict_reason ?? '',
    decision_requested: `Should #${h.display_tag} be researched with the top 25, or dropped from this run?`,
    options: ['Approve', 'Reject'],
    resolved: false,
    resolved_by: null,
    resolved_at: null,
    outcome: null,
    created_at: minutesAgo(ri(35, 210)),
    entity_title: `#${h.display_tag}`,
  })
}
for (const s of scraped.filter((x) => x.validation === 'needs_review').slice(0, 4)) {
  reviewQueue.push({
    id: id('rq'),
    kind: 'scraped_item',
    entity_id: s.id,
    reason: s.verdict_reason ?? '',
    decision_requested: `Is "${s.title}" relevant enough to inform this week's calendar?`,
    options: ['Approve', 'Reject'],
    resolved: false,
    resolved_by: null,
    resolved_at: null,
    outcome: null,
    created_at: minutesAgo(ri(40, 230)),
    entity_title: s.title,
  })
}

/* ═══════════════════════════════════════════════════════════════════════════
   Ethara — six turns covering the full range
   ═══════════════════════════════════════════════════════════════════════════ */

const conversationId = id('conv')

const assistantTurns: AssistantTurn[] = [
  {
    id: id('turn'),
    seq: 1,
    speaker: 'operator',
    utterance: "What's trending this week?",
    channel: 'text',
    narration: null,
    confidence: null,
    status: 'completed',
    created_at: hoursAgo(5),
  },
  {
    id: id('turn'),
    seq: 2,
    speaker: 'assistant',
    utterance: '',
    channel: 'text',
    narration:
      'Five keywords are trending. `agentic AI` leads on engagement velocity — up 68% on its four-run average across 41 posts. `reward modeling` is second and growing fastest at 52%. Twenty-five hashtags are queued for research.',
    confidence: 94,
    status: 'completed',
    created_at: hoursAgo(5),
    plan: {
      id: id('plan'),
      summary: 'Read the current trending keywords with their scores and reasons.',
      risk: 'safe',
      requiresConfirmation: false,
      restated: 'Show the top five trending keywords for this run.',
      confidence: 94,
      parser: 'grammar',
      steps: [
        { idx: 0, toolId: 'keyword.trending', toolName: 'Trending keywords', risk: 'safe', why: 'The question is exactly what this tool returns.', agentId: 'validation', status: 'completed', summary: '5 keywords returned', render: 'table' },
      ],
    },
  },
  {
    id: id('turn'),
    seq: 3,
    speaker: 'operator',
    utterance: "Draft Thursday's LinkedIn post and put the creative next to it.",
    channel: 'voice',
    narration: null,
    confidence: null,
    status: 'completed',
    created_at: hoursAgo(4),
  },
  {
    id: id('turn'),
    seq: 4,
    speaker: 'assistant',
    utterance: '',
    channel: 'voice',
    narration:
      'Done. "Calibration beats capacity in critics" is drafted for Thursday 09:00 and the creative is rendered at 1200×627. The caption is grounded in two Knowledge Base entries on critic calibration. The image used the local brand renderer — no image model is configured.',
    confidence: 88,
    status: 'completed',
    created_at: hoursAgo(4),
    plan: {
      id: id('plan'),
      summary: "Find Thursday's LinkedIn idea, write its caption, then render the creative.",
      risk: 'mutating',
      requiresConfirmation: false,
      restated: "Draft the LinkedIn post scheduled for Thursday and render its image.",
      confidence: 88,
      parser: 'grammar',
      steps: [
        { idx: 0, toolId: 'idea.list', toolName: 'List ideas', risk: 'safe', why: 'Read before write: the draft needs the idea it belongs to.', agentId: 'calendar', status: 'completed', summary: '1 idea matched Thursday on LinkedIn', render: 'table' },
        { idx: 1, toolId: 'draft.generate', toolName: 'Generate draft', risk: 'mutating', why: 'Write the caption grounded in the Knowledge Base.', agentId: 'caption', status: 'completed', summary: 'Draft written, revision 1', render: 'draft' },
        { idx: 2, toolId: 'image.render', toolName: 'Render creative', risk: 'mutating', why: 'The operator asked for the creative alongside the copy.', agentId: 'image', status: 'completed', summary: 'Rendered 1200×627 with brand-svg', render: 'media', fallbackReason: 'No image model configured — GCP_API_KEY and Z_IMAGE_ENDPOINT are both unset.' },
      ],
    },
  },
  {
    id: id('turn'),
    seq: 5,
    speaker: 'operator',
    utterance: 'Publish it.',
    channel: 'text',
    narration: null,
    confidence: null,
    status: 'completed',
    created_at: hoursAgo(3),
  },
  {
    id: id('turn'),
    seq: 6,
    speaker: 'assistant',
    utterance: '',
    channel: 'text',
    narration:
      'Published to LinkedIn at 10:32. The Analytics Agent will report the first reading in an hour. I have written the approval to the Knowledge Base.',
    confidence: 91,
    status: 'completed',
    created_at: hoursAgo(3),
    plan: {
      id: id('plan'),
      summary: 'Check the draft against the twenty rules, then publish it to LinkedIn.',
      risk: 'irreversible',
      requiresConfirmation: true,
      restated: 'Publish the Thursday LinkedIn draft now.',
      confidence: 91,
      parser: 'grammar',
      steps: [
        { idx: 0, toolId: 'brand.check', toolName: 'Brand voice check', risk: 'safe', why: 'Nothing irreversible runs before the compliance read.', agentId: 'review', status: 'completed', summary: 'APPROVED · no violations', render: 'compliance' },
        { idx: 1, toolId: 'idea.publish', toolName: 'Publish now', risk: 'irreversible', why: 'The operator asked for it explicitly and confirmed.', agentId: 'publishing', status: 'completed', summary: 'Published in demo mode · receipt recorded', render: 'receipt' },
      ],
    },
  },
]

const assistantBrief: AssistantBrief = {
  id: id('brief'),
  trigger: 'cron',
  signals: [
    { label: 'Leadership queue', detail: 'Three posts await Leadership, the oldest since yesterday.' },
    { label: 'Knowledge base', detail: `The Sunday research build added ${RESEARCH.length} cited entries.` },
    { label: 'Instagram reach', detail: 'Down 14% against its four-week average, concentrated in non-follower views.' },
  ],
  recommendation: "Move Thursday's carousel to Tuesday — Tuesday 10:30 carries 34% higher median reach on this account.",
  narration:
    '09:00. Three posts await Leadership, the Sunday research build added fifteen cited entries, and Instagram reach is 14% below its trailing average. I would move Thursday\'s carousel to Tuesday.',
  created_at: hoursAgo(2),
}

/* ═══════════════════════════════════════════════════════════════════════════
   THE PAYLOAD
   ═══════════════════════════════════════════════════════════════════════════ */

export const DEMO_STATE: StatePayload = {
  workspace: {
    name: 'Ethara.AI',
    slug: 'ethara',
    brandVoice: BRAND.voiceWords.join(', '),
    audience: BRAND.audience,
    settings: {},
  },
  keywords,
  keywordSignals: keywordSignals.filter((s) => s.run_id === latestRunId),
  hashtags,
  topHashtags,
  scraped,
  ideas,
  drafts,
  media,
  published,
  knowledge,
  knowledgeBuild,
  agents,
  activity,
  analytics,
  reviewQueue,
  sources,
  pipeline: {
    id: latestRunId ?? id('run'),
    trigger: 'seed',
    status: 'completed',
    turn_id: null,
    started_at: minutesAgo(216),
    finished_at: minutesAgo(196),
    summary: {
      keywordsScanned: 12,
      postsScraped: scraped.length,
      hashtagsFound: hashtags.length,
      trending: 5,
      validated: scraped.filter((s) => s.validation === 'validated').length,
      needsReview: scraped.filter((s) => s.validation === 'needs_review').length,
      duplicate: scraped.filter((s) => s.validation === 'duplicate').length,
      rejected: scraped.filter((s) => s.validation === 'rejected').length,
      topHashtags: topHashtags.length,
      opportunities: 9,
      ideas: ideas.length,
      primaryIdeas: ideas.filter((i) => i.calendar_slot === 'primary').length,
      suggestionIdeas: ideas.filter((i) => i.calendar_slot === 'suggestion').length,
      source: 'fixture',
    },
  },
  platformLabels: { linkedin: 'LinkedIn', instagram: 'Instagram', x: 'X', facebook: 'Facebook' },
  assistant: {
    conversation: {
      id: conversationId,
      actor: 'Ridhima',
      role: 'marketing',
      title: "What's trending this week?",
      started_at: hoursAgo(5),
      last_at: hoursAgo(3),
      turn_count: assistantTurns.length,
      tool_count: 6,
    },
    turns: assistantTurns,
    brief: assistantBrief,
    pendingConfirm: null,
  },
  mode: {
    publishMode: 'demo',
    assistantProvider: 'deterministic',
    integrations: [
      { id: 'apify', label: 'Apify · LinkedIn scraping', configured: false, reason: 'APIFY_API_TOKEN is not set' },
      { id: 'parallel', label: 'Parallel Web Systems · deep research', configured: false, reason: 'PARALLEL_API_KEY is not set' },
      { id: 'gcp', label: 'Google Cloud · Gemini and Imagen', configured: false, reason: 'GCP_API_KEY is not set' },
      { id: 'z-image', label: 'Z-Image Turbo', configured: false, reason: 'Z_IMAGE_ENDPOINT is not set' },
    ],
  },
}

/** Ambient notices Ethara would raise on this dataset. Used in standalone mode. */
export const DEMO_NOTICES = [
  {
    id: id('notice'),
    signal: 'review-queue',
    message: `${reviewQueue.length} items have been waiting on a verdict for half an hour. I can walk you through them.`,
    severity: 'warn' as const,
    action: { label: 'Show me', utterance: 'Show me everything waiting on me' },
    at: minutesAgo(12),
  },
  {
    id: id('notice'),
    signal: 'metric-anomaly',
    message: 'Instagram reach is 14% below its four-week average; the drop is concentrated on non-follower views.',
    severity: 'serious' as const,
    action: { label: 'Explain', utterance: 'Why did Instagram drop last month?' },
    at: minutesAgo(31),
  },
]
